version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
    - echo Build started on `date`
    - echo Building the Docker images...
    - docker build -t examplevotingapp_vote vote
    - docker build -t examplevotingapp_worker worker
    - docker build -t examplevotingapp_result result
    - docker tag examplevotingapp_vote:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/examplevotingapp_vote:latest
    - docker tag examplevotingapp_worker:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/examplevotingapp_worker:latest
    - docker tag examplevotingapp_result:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/examplevotingapp_result:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/examplevotingapp_vote:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/examplevotingapp_worker:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/examplevotingapp_result:latest
