version: 0.2
  phases:
    pre_build:
      commands:
        - echo Logging in to Amazon ECR...
        - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
    build:
      commands:
      - echo Build started on `date`
      - echo Building the Docker images...
      - CUSTOM_TAG=$(date +%s)
      - docker build -t dockersamples/examplevotingapp_vote:$CUSTOM_TAG vote
      - docker build -t dockersamples/examplevotingapp_worker:$CUSTOM_TAG worker
      - docker build -t dockersamples/examplevotingapp_result:$CUSTOM_TAG result
    post_build:
      commands:
        - echo Build completed on `date`
        - echo Pushing the Docker images...
        - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/examplevotingapp_vote:$CUSTOM_TAG
        - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/examplevotingapp_worker:$CUSTOM_TAG
        - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/examplevotingapp_result:$CUSTOM_TAG
