apiVersion: v1
kind: Service
metadata:
  name: result
  namespace: vote
  annotations:
    external-dns.alpha.kubernetes.io/hostname: result.voting.kloia.com.
spec:
  type: LoadBalancer
  ports:
  - name: "result-service"
    port: 80
    targetPort: 80
    nodePort: 31001
  selector:
    app: result
