apiVersion: v1
kind: Service
metadata:
  name: vote
  namespace: vote
  annotations:
    external-dns.alpha.kubernetes.io/hostname: vote.voting.kloia.com.
    external-dns.alpha.kubernetes.io/ttl: 10
spec:
  type: LoadBalancer
  ports:
  - name: "vote-service"
    port: 80
    targetPort: 80
    nodePort: 31000
  selector:
    app: vote
